[tool.poetry]
name = "name"
version = "0.1.0"
description = "name"
authors = ["name"]

[tool.poetry.dependencies]
python = "^3.8"
oddrn-generator = "^0.1.22"
odd-models = "^1.0.15"
odd-collector-sdk = "^0.1.1"
psycopg2-binary = "^2.9.3"
clickhouse-driver = "^0.2.3"
mysql-connector-python = "^8.0.28"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
