[tool.poetry]
name = "odd-collector"
version = "0.1.0"
description = "ODD Collector"
authors = ["Open Data Discovery <pypi@opendatadiscovery.org>"]
homepage = "https://github.com/opendatadiscovery/odd-collector"
repository = "https://github.com/opendatadiscovery/odd-collector"



[tool.poetry.dependencies]
python = "^3.8"
oddrn-generator = "^0.1.22"
odd-models = "^1.0.15"
odd-collector-sdk = "^0.1.3"
psycopg2-binary = "^2.9.3"
clickhouse-driver = "^0.2.3"
mysql-connector-python = "^8.0.28"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
