version: "3.8"
services:
  odd-collector:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: odd-generic-collector
    restart: always
    environment:
      # FLASK:
      - FLASK_ENVIRONMENT=${FLASK_ENVIRONMENT}
    ports:
      - "127.0.0.1:8080:8080"
